application: energytrak-prototype
version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
- url: /js
  static_dir: js
- url: /stylesheets
  static_dir: stylesheets
- url: /images
  static_dir: images
- url: /admin.*
  script: energytrak.application
  login: admin
- url: /.*
  script: energytrak.application
# [END handlers]

# [START libraries]
libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
# [END libraries]